### ISSUE TITLE
Updated Website-First Pages

### ISSUE THREAD

**Issue by namodya** [SaumyaSM/ComputingGroupProject#1]

**Comment by namodya** [comment]
[Uploading Wesite(HomePages).zip…]()

**Comment by Sheshaniiz** [comment]
[Wesite(HomePages).zip](https://github.com/SaumyaSM/ComputingGroupProject/files/14628593/Wesite.HomePages.zip)

**Comment by namodya** [comment]
[website.zip](https://github.com/SaumyaSM/ComputingGroupProject/files/14636573/website.zip)
updated package

**Comment by SaumyaSM** [comment]
[WEBSITE (2).zip](https://github.com/SaumyaSM/ComputingGroupProject/files/14637610/WEBSITE.2.zip)
updated
